[package]
name = "cuda_sparse"
version = "0.1.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
#build = "build.rs"

[lib]
name = "cuda_sparse"
path = "src/lib.rs"

[dependencies]
libc = "*"
#cuda = { path = "../libcuda" }
cuda = { git = "https://github.com/peterhj/libcuda.git" }
